services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "/data/fabric-server-mc.1.20.1-loader.0.18.4-launcher.1.1.1.jar"
    ports:
      - "25565:25565"
    volumes:
      - ./fabric-server-mc.1.20.1-loader.0.18.4-launcher.1.1.1.jar:/data/fabric-server-mc.1.20.1-loader.0.18.4-launcher.1.1.1.jar:ro
      - ./mods:/data/mods
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

  mod-manager:
    build: ./mod-manager
    ports:
      - "3000:3000"
    volumes:
      - ./mods:/app/mods
    environment:
      MODS_DIR: "/app/mods"
    restart: unless-stopped

volumes:
  data: {}